sudo: required
services:
  - docker

before_install:
  - docker build -t skdhanjal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skdhanjal/react-test npm test

after_success:
  - docker build -t skdhanjal/multi-client ./client
  - docker build -t skdhanjal/multi-nginx ./nginx
  - docker build -t skdhanjal/multi-server ./server
  - docker build -t skdhanjal/multi-worker ./worker
# Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take these images and push them to docker hub
  - docker push skdhanjal/multi-client
  - docker push skdhanjal/multi-nginx
  - docker push skdhanjal/multi-server
  - docker push skdhanjal/multi-worker